materials:
- name: stone
  albedo: [ 0.5, 0.5, 0.5 ]
  roughness: 0.8
  metallic: 0
  texture: tiles.jpg
  tiling: 5
- name: metal
  albedo: [ 0.8, 0.8, 0.8 ]
  roughness: 0.2
  metallic: 1
  texture: wood.jpg
  tiling: 0.5

entities:
- name: scene_root
  type: empty
  transform:
    position: [ 0, 0, 0 ]
    rotation: [ 0, 0, 0, 1 ]
    scale: [ 1, 1, 1 ]
  children:
    - name: ground
      type: mesh
      transform:
        position: [ 0, -1, 0 ]
        rotation: [ 0, 0, 0, 1 ]
        scale: [ 10, 1, 10 ]
      mesh: ground.obj
      material: 0
    - name: cube
      type: mesh
      transform:
        position: [ 2, 1, 0 ]
        rotation: [ 0, 0.7071, 0, 0.7071 ]
        scale: [ 1, 1, 1 ]
      mesh: cube.obj
      material: 1
    - name: lighting_group
      type: empty
      transform:
        position: [ -0.909, 5, 5 ]
        rotation: [ -0.643505, 0.0327726, 0, 0.76474 ]
        scale: [ 3.61, 1, 1 ]
      children:
        - name: sun
          type: light
          transform:
            position: [ 0, 0, 0 ]
            rotation: [ 0, 0, 0, 1 ]
            scale: [ 1, 1, 1 ]
          light_color: [ 1, 1, 1 ]
          light_intensity: 1.5
          light_type: 0
          light_direction: [ 0, 0, -1 ]
        - name: point_light
          type: light
          transform:
            position: [ 0, 0, 0 ]
            rotation: [ 0, 0, 0, 1 ]
            scale: [ 1, 1, 1 ]
          light_color: [ 0.729107, 0.518529, 0.275254 ]
          light_intensity: 1.798
          light_type: 1
          light_radius: 19.074
